server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848         #Nacos服务注册中心地址
    sentinel:
     transport:
       dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
       port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
     web-context-unify: false # controller层的方法对service层调用不认为是同一个根链路
     datasource: #sentinel持久化配置
       ds1:
        nacos:
         server-addr: localhost:8848
         dataId: ${spring.application.name}
         groupId: DEFAULT_GROUP
         data-type: json
         rule-type: flow
#        ds1: #自定义key ，也可以叫做限流类型等等
#          nacos:
#            server-addr: localhost:8848 #nacos地址
#            dataId: ${spring.application.name} #nacos配置里面的
#            groupId: DEFAULT_GROUP  #nacos配置里面的
#            data-type: json     #nacos配置里面的
#            rule-type: flow  #此处为流控规则，具体类型